# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
nginx_package_name:
  - certbot
  - nginx

# windmill.zuul
zuul_file_web_logging_conf_manage: true

zuul_file_zuul_web_service_manage: true

zuul_pip_name: zuul[mysql_reporter]

zuul_service_zuul_web_enabled: true
zuul_service_zuul_web_manage: true
zuul_service_zuul_web_state: started

# openstack.logrotate
logrotate_configs:
  - name: zuul-web
    log: /var/log/zuul/web-debug.log /var/log/zuul/web.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty

nginx_file_nginx_config:
  - dest: /etc/nginx/sites-available/dashboard-ssl
    src: "{{ windmill_config_git_dest }}/zuul/etc/nginx/sites-available/dashboard-ssl.j2"
  - dest: /etc/nginx/sites-available/default
    src: "{{ windmill_config_git_dest }}/zuul/etc/nginx/sites-available/default.j2"
  - dest: /etc/nginx/sites-available/logs-ssl
    src: "{{ windmill_config_git_dest }}/zuul/etc/nginx/sites-available/logs-ssl.j2"

_iptables_public_tcp_ports_extra:
  - 80
  - 443
