---
- hosts: localhost
  tasks:
    - name: Add bastion server
      add_host:
        name: "{{ site_windmill_config_bastion.fqdn }}"
        ansible_user: "{{ site_windmill_config_bastion.ssh_username }}"
        group: bastion

    - name: Add bastion server to known hosts
      known_hosts:
        name: "{{ site_windmill_config_bastion.fqdn }}"
        key: "{{ site_windmill_config_bastion.ssh_known_hosts }}"

- hosts: bastion
  tasks:
    - name: Bootstrap tox environment
      args:
        chdir: ~/src/git.openstack.org/openstack/windmill
      shell: "{{ ansible_user_dir }}/.local/bin/tox -evenv --notest"
